---
- name: start k8s cluster / Control-Planes
  hosts: control_plane_first
  become: yes
  become_user: root
  tasks:

    - name: cleaning existing installation
      ansible.builtin.command: kubeadm reset -f

    - name: generate certificate key for control-planes
      ansible.builtin.command: kubeadm certs certificate-key
      register: control_plane_cert_key

    - name: start
      ansible.builtin.command: kubeadm init --control-plane-endpoint "svck8sctrlpln001.privcloud.vsf" --upload-certs --certificate-key {{ control_plane_cert_key.stdout }}
      
    - name: creation directory .kube
      ansible.builtin.file:
        path: ~/.kube
        state: directory
        owner: root
        group: root
        mode: 0644

    - name: copy kube config file
      ansible.builtin.copy: 
        src: /etc/kubernetes/admin.conf
        dest: ~/.kube/config
        remote_src: yes
        owner: root
        group: root
        mode: 0640
         
    - name: apply Weave Net
      ansible.builtin.command: kubectl apply -f https://github.com/weaveworks/weave/releases/download/v2.8.1/weave-daemonset-k8s.yaml

    - name: join command
      ansible.builtin.shell: kubeadm token create --print-join-command
      register: join_variable_print

    - name: Print Join Command
      ansible.builtin.debug:
        msg: join comand is {{join_variable_print.stdout}}

    - name: add join in fact
      ansible.builtin.set_fact: 
        join_command: "{{join_variable_print.stdout}}"
        cert_key: "{{ control_plane_cert_key.stdout }}"

- name: start k8s cluster / Master_Nodes
  hosts: master_nodes
  become: yes
  become_user: root
  tasks:

    - name: cleaning existing installation
      ansible.builtin.command: kubeadm reset -f

    - name: Play command join 
      ansible.builtin.command: "{{hostvars[groups['control_plane_first'][0]]['join_command']}} --control-plane --certificate-key {{hostvars[groups['control_plane_first'][0]]['cert_key']}}"
